import {
  Activity,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Check,
  ChevronRight,
  ClipboardList,
  Clock,
  EyeOff,
  LogOut,
  MessageCircle,
  Monitor,
  Moon,
  Pencil,
  Phone,
  Settings,
  Sun,
  User,
  Users,
} from '@lucide/vue'

export const iconos = {
  activar: Check,
  ajustes: Settings,
  calendario: CalendarDays,
  clinica: Building2,
  desactivar: EyeOff,
  editar: Pencil,
  especialidad: ClipboardList,
  horario: Clock,
  mensaje: MessageCircle,
  monitor: Monitor,
  luna: Moon,
  perfil: User,
  sol: Sun,
  operaciones: Activity,
  profesional: BriefcaseBusiness,
  salir: LogOut,
  usuarios: Users,
  telefono: Phone,
  siguiente: ChevronRight,
} as const

export type NombreIcono = keyof typeof iconos
